# 1.Problem Statement

- In today’s fitness industry, understanding customer behavior is crucial for improving subscription rates and user engagement. Gym and fitness app platforms collect various user data such as workout habits, app usage time, diet preferences, and fitness levels.

- The problem is to develop a classification model using Decision Tree Classifier that can predict whether a user will purchase a premium subscription (Subscription_Status) based on features like:

   - Age
   - Monthly Income
   - Workout Frequency
   - App Usage Time
   - Trial Days Used
   - Preferred Workout
   - Diet Type
   - Fitness Level
   - Device Type

- The goal is to assist businesses in identifying potential subscribers and improving targeted marketing strategies.

# 2.Objective

The main objectives of this project are:

- To analyze user behavior and identify patterns influencing subscription decisions
- To preprocess the dataset:
   - Handle categorical variables using encoding techniques
   - Prepare data for model training
- To build a Decision Tree Classifier model for predicting subscription status (0 or 1)
- To evaluate model performance using classification metrics:
   - Accuracy
   - Precision
   - Recall
   - F1 Score
- To understand the importance of features and decision rules generated by the model
- To reduce overfitting by tuning hyperparameters such as:
   - max_depth
   - min_samples_split
   - min_samples_leaf

## 3.Import Libraries

In [48]:
import numpy as np
import pandas as pd

## 4.Load Dataset

In [49]:
df = pd.read_csv("fitness_subscription_dataset.csv")
df.head()

,User_ID,Age,Monthly_Income,Workout_Frequency,Preferred_Workout,Diet_Type,Fitness_Level,App_Usage_Time,Trial_Days_Used,Device_Type,Subscription
0,U0238,23,34061,6,Yoga,Vegan,Advanced,49,13,Android,0
1,U0019,27,18986,5,Crossfit,Keto,Intermediate,7,10,Android,1
2,U0281,22,56081,5,Yoga,Non-Veg,Advanced,80,8,iOS,1
3,U0508,49,68493,1,Cardio,Vegetarian,Intermediate,44,1,iOS,0
4,U0428,39,40873,3,Strength,Keto,Intermediate,45,1,Android,0

## 5.Check Missing Values

In [50]:
df.isnull().sum()

User_ID              0
Age                  0
Monthly_Income       0
Workout_Frequency    0
Preferred_Workout    0
Diet_Type            0
Fitness_Level        0
App_Usage_Time       0
Trial_Days_Used      0
Device_Type          0
Subscription         0
dtype: int64

## 6.Preprocessing

### i) One-Hot Encoding

In [51]:
df = pd.get_dummies(df,columns=["Preferred_Workout","Diet_Type"]) # One-hot encoder
df

,User_ID,Age,Monthly_Income,Workout_Frequency,Fitness_Level,App_Usage_Time,Trial_Days_Used,Device_Type,Subscription,Preferred_Workout_Cardio,Preferred_Workout_Crossfit,Preferred_Workout_Strength,Preferred_Workout_Yoga,Diet_Type_Keto,Diet_Type_Non-Veg,Diet_Type_Vegan,Diet_Type_Vegetarian
0,U0238,23,34061,6,Advanced,49,13,Android,0,False,False,False,True,False,False,True,False
1,U0019,27,18986,5,Intermediate,7,10,Android,1,False,True,False,False,True,False,False,False
2,U0281,22,56081,5,Advanced,80,8,iOS,1,False,False,False,True,False,True,False,False
3,U0508,49,68493,1,Intermediate,44,1,iOS,0,True,False,False,False,False,False,False,True
4,U0428,39,40873,3,Intermediate,45,1,Android,0,False,False,True,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,U0495,32,52522,1,Advanced,5,10,iOS,0,True,False,False,False,False,False,True,False
596,U0475,32,84170,0,Intermediate,95,8,Android,0,False,True,False,False,True,False,False,False
597,U0274,39,20791,0,Intermediate,18,9,Android,0,False,True,False,False,False,False,True,False
598,U0547,37,84244,5,Advanced,34,3,iOS,1,True,False,False,False,False,True,False,False
599,U0088,25,50078,1,Advanced,41,1,Android,0,False,False,False,True,False,False,False,True

### ii) Label Encoding

In [52]:
df["Fitness_Level"] = df["Fitness_Level"].map({
    "Advanced":2,
    "Intermediate":1,
    "Beginner":0
})

df["Device_Type"] = df["Device_Type"].map({
    "iOS":1,
    "Android":0
})

## 7.Model Building

### i) Seperate Target & Feature

In [53]:
X = df.drop(["Subscription","User_ID"],axis=1)
y= df["Subscription"]

### ii) Split The Dataset

In [54]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=42)

### iii) Select Model

In [55]:
from sklearn.tree import DecisionTreeClassifier

In [56]:

from sklearn.tree import DecisionTreeClassifier

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(
    criterion='gini',
    max_depth=6,
    min_samples_split=10,
    min_samples_leaf=5,
    class_weight='balanced',
    random_state=42
)

### iv) Train Model

In [57]:
model.fit(X_train,y_train)

DecisionTreeClassifier(class_weight='balanced', max_depth=6, min_samples_leaf=5,
                       min_samples_split=10, random_state=42)

## 8.Predict

In [58]:
y_pred = model.predict(X_test)
print(y_pred)

[0 1 1 0 0 0 0 0 1 1 0 0 1 1 0 0 1 1 0 1 1 0 1 0 0 0 1 1 1 0 1 1 1 0 0 1 1
 1 0 1 1 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 0 1 0 1 1 0 0 1 1 1 0 1 1 1 1 0 1
 1 1 1 1 0 1 1 0 0 1 1 0 1 1 0 1 0 0 0 1 0 1 0 0 1 0 0 1 0 0 1 1 0 0 1 0 0
 0 0 0 0 0 0 1 0 0]

## 9.Evaluation

In [59]:
from sklearn.metrics import accuracy_score,classification_report

print("accuracy_score:",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred,output_dict=True))

accuracy_score: 0.625
{'0': {'precision': 0.6129032258064516, 'recall': 0.6440677966101694, 'f1-score': 0.628099173553719, 'support': 59.0}, '1': {'precision': 0.6379310344827587, 'recall': 0.6065573770491803, 'f1-score': 0.6218487394957983, 'support': 61.0}, 'accuracy': 0.625, 'macro avg': {'precision': 0.6254171301446052, 'recall': 0.6253125868296749, 'f1-score': 0.6249739565247587, 'support': 120.0}, 'weighted avg': {'precision': 0.6256256952169077, 'recall': 0.625, 'f1-score': 0.624921869574276, 'support': 120.0}}