# Decision Tree Regressor

## 1.Problem Statement

- The real estate market involves multiple factors such as house size, number of bedrooms, location, condition, and furnishing status that influence property prices. Accurately estimating house prices is essential for buyers, sellers, and real estate agents.

- The problem is to develop a predictive model using Decision Tree Regressor that can estimate the house price (house_price_usd) based on input features like:

- house size (sqft)
- number of bedrooms
- age of house
- location
- house type
- condition
- furnishing status

## 2.Objectives

- To analyze the relationship between house features and house prices
- To preprocess the dataset (handling categorical variables, scaling if needed)
- To build a Decision Tree Regressor model for predicting house prices
- To evaluate the model using metrics like:
     - Mean Squared Error (MSE)
     - R² Score
- To optimize model performance by tuning hyperparameters like:
     - max_depth
     - min_samples_split
     - min_samples_leaf

## 3.Import Libraries

In [1]:
import numpy as np
import pandas as pd

C:\Users\yashk\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

## 4.Load Dataset

In [2]:
df = pd.read_csv("ml_pipeline_practice.csv")

In [3]:
df.head()

,id,house_size_sqft,num_bedrooms,age_of_house_years,location,house_type,condition,furnishing,house_price_usd
0,1,3377.42,1,47,Suburban,Villa,Average,Unfurnished,614992.29
1,2,4514.81,1,37,Suburban,Apartment,Poor,Unfurnished,735642.67
2,3,1483.87,5,38,Urban,Villa,Excellent,Unfurnished,417046.99
3,4,4411.85,2,44,Suburban,Bungalow,Good,Unfurnished,772604.15
4,5,1468.91,3,6,Urban,Townhouse,Poor,Semi-Furnished,384795.11

## 5.Check Missing Values

In [4]:
df.isnull().sum()

id                    0
house_size_sqft       0
num_bedrooms          0
age_of_house_years    0
location              0
house_type            0
condition             0
furnishing            0
house_price_usd       0
dtype: int64

## 6.Preprocessing

### i) One-Hot Encoding

In [5]:
df = pd.get_dummies(df,columns=["location","house_type"]) # One-hot encoder
df

,id,house_size_sqft,num_bedrooms,age_of_house_years,condition,furnishing,house_price_usd,location_Rural,location_Suburban,location_Urban,house_type_Apartment,house_type_Bungalow,house_type_Townhouse,house_type_Villa
0,1,3377.42,1,47,Average,Unfurnished,614992.29,False,True,False,False,False,False,True
1,2,4514.81,1,37,Poor,Unfurnished,735642.67,False,True,False,True,False,False,False
2,3,1483.87,5,38,Excellent,Unfurnished,417046.99,False,False,True,False,False,False,True
3,4,4411.85,2,44,Good,Unfurnished,772604.15,False,True,False,False,True,False,False
4,5,1468.91,3,6,Poor,Semi-Furnished,384795.11,False,False,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,746,1962.03,4,56,Excellent,Unfurnished,443623.97,False,False,True,False,False,True,False
746,747,3235.68,4,46,Poor,Furnished,616387.20,False,True,False,False,False,True,False
747,748,4449.95,2,33,Poor,Furnished,767697.79,True,False,False,False,False,True,False
748,749,2243.29,6,3,Excellent,Semi-Furnished,568403.41,False,False,True,False,True,False,False
749,750,1786.62,2,27,Average,Semi-Furnished,367234.00,False,True,False,True,False,False,False

### ii) Label Encoding

In [6]:
df["condition"] = df["condition"].map({
    "Poor": 0,
    "Average": 1,
    "Good": 2,
    "Excellent": 3
})

df["furnishing"] = df["furnishing"].map({
    "Unfurnished": 0,
    "Semi-Furnished": 1,
    "Furnished": 2
})

In [7]:
df = df.astype(int)

In [8]:
print(df.columns)

Index(['id', 'house_size_sqft', 'num_bedrooms', 'age_of_house_years',
       'condition', 'furnishing', 'house_price_usd', 'location_Rural',
       'location_Suburban', 'location_Urban', 'house_type_Apartment',
       'house_type_Bungalow', 'house_type_Townhouse', 'house_type_Villa'],
      dtype='str')

## 7.Model Building

### i) Seperate Target & Feature

In [9]:
X = df.drop(["house_price_usd","id"],axis=1)
y = df["house_price_usd"]

### ii) Split The Dataset

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=42)

### iii) Select Model

In [12]:
from sklearn.tree import DecisionTreeRegressor

In [13]:
model = DecisionTreeRegressor(max_depth=3)

### iv) Train Model

In [14]:
model.fit(X_train,y_train)

DecisionTreeRegressor(max_depth=3)

## 8.Predict

In [15]:
y_pred = model.predict(X_test)
print(y_pred)

[413793.63333333 679605.51648352 841470.45454545 252151.23214286
 512913.50724638 756127.97959184 314702.84848485 841470.45454545
 512913.50724638 314702.84848485 679605.51648352 583893.1
 841470.45454545 679605.51648352 512913.50724638 756127.97959184
 841470.45454545 413793.63333333 252151.23214286 841470.45454545
 679605.51648352 841470.45454545 756127.97959184 679605.51648352
 583893.1        756127.97959184 756127.97959184 679605.51648352
 512913.50724638 252151.23214286 756127.97959184 252151.23214286
 679605.51648352 314702.84848485 679605.51648352 679605.51648352
 252151.23214286 512913.50724638 413793.63333333 679605.51648352
 314702.84848485 756127.97959184 841470.45454545 841470.45454545
 756127.97959184 413793.63333333 512913.50724638 512913.50724638
 314702.84848485 841470.45454545 512913.50724638 314702.84848485
 512913.50724638 314702.84848485 252151.23214286 841470.45454545
 583893.1        413793.63333333 252151.23214286 679605.51648352
 756127.97959184 756127.97959184 413793.63333333 841470.45454545
 413793.63333333 583893.1        314702.84848485 252151.23214286
 314702.84848485 679605.51648352 583893.1        314702.84848485
 841470.45454545 413793.63333333 314702.84848485 756127.97959184
 841470.45454545 841470.45454545 679605.51648352 512913.50724638
 314702.84848485 583893.1        512913.50724638 841470.45454545
 252151.23214286 512913.50724638 413793.63333333 841470.45454545
 252151.23214286 841470.45454545 841470.45454545 679605.51648352
 679605.51648352 413793.63333333 413793.63333333 413793.63333333
 756127.97959184 841470.45454545 252151.23214286 583893.1
 756127.97959184 512913.50724638 413793.63333333 413793.63333333
 314702.84848485 413793.63333333 314702.84848485 314702.84848485
 756127.97959184 756127.97959184 756127.97959184 252151.23214286
 252151.23214286 756127.97959184 512913.50724638 512913.50724638
 679605.51648352 314702.84848485 679605.51648352 252151.23214286
 679605.51648352 413793.63333333 679605.51648352 512913.50724638
 314702.84848485 512913.50724638 841470.45454545 841470.45454545
 841470.45454545 512913.50724638 512913.50724638 841470.45454545
 583893.1        756127.97959184 413793.63333333 583893.1
 413793.63333333 583893.1        512913.50724638 314702.84848485
 583893.1        314702.84848485 841470.45454545 413793.63333333
 756127.97959184 756127.97959184 679605.51648352 679605.51648352
 679605.51648352 841470.45454545]

## 9.Evaluation

In [16]:
from sklearn.metrics import mean_absolute_error,r2_score
MAE = mean_absolute_error(y_test,y_pred)
R2 = r2_score(y_test,y_pred)

print("MAE:",MAE)
print("R2:",R2)

MAE: 35969.16361752878
R2: 0.9533270250993099